#!/usr/bin/env bash

set -o errexit
set -o pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker compose
# commands that enable it by default, such as exec and run.
TTY="${TTY:-}"
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker compose "${DC}" ${TTY} "${@}"
}

function _dc_run {
   DC="run" _dc --no-deps --rm "${@}"
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the web container
  _dc web "${@}"
}


function shell {
  # Start a shell session in the web container
  cmd bash "${@}"
}

function hadolint {
  # Lint Dockerfile with hadolint
  docker container run --rm -i \
    hadolint/hadolint hadolint --ignore DL3008 -t style "${@}" - < Dockerfile
}

function deps:install {
  local no_build="${1:-}"

  [ -z "${no_build}" ] && docker compose down && docker compose build

  _dc_run js yarn install
  _dc_run web bundle install
}

function bundle {
  cmd bundle "${@}"
}

function bundle:outdated {
  # List any installed gems that are outdated
  _dc_run web bundle outdated
}

function bundle:update {
  # Update any installed gems that are outdated
  _dc_run web bundle update
  deps:install "${@}"
}

function yarn {
  _dc js yarn "${@}"
}

function yarn:outdated {
  # Install yarn dependencies and write lock file
  _dc_run js yarn outdated
}

function yarn:build {
  # Build JS assets, this is only meant to be referenced from your package.json
  local args=()

  if [ "${NODE_ENV:-}" == "production" ]; then
    args=(--minify)
  elif [ "${RAILS_ENV:-}" == "development" ]; then
    args=(--sourcemap --watch)
  fi

  esbuild ./assets/javascript/*.* --outdir=./assets/builds --bundle "${args[@]}"
}

function yarn:build:css {
  # Build CSS assets, this is only meant to be referenced from your package.json
  local args=()

  if [ "${NODE_ENV:-}" == "production" ]; then
    args=(--minify)
  elif [ "${RAILS_ENV:-}" == "development" ]; then
    args=(--watch)
  fi

  tailwindcss \
    -i ./assets/stylesheets/application.css \
    -o ./assets/builds/application.css "${args[@]}"
}

function clean {
  # Remove cache and other machine generates files
  rm -rf node_modules/ ./assets/builds/* ./_site/ ./.jekyll-cache
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
